// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	PhotoURL   string `json:"photoURL"`
	BannerURL  string `json:"bannerURL"`
	Subscriber int    `json:"subscriber"`
	IsPremium  string `json:"isPremium"`
}

type Video struct {
	VideoID         string `json:"videoId"`
	VideoTitle      string `json:"videoTitle"`
	VideoDesc       string `json:"videoDesc"`
	VideoURL        string `json:"videoURL"`
	VideoThumbnail  string `json:"videoThumbnail"`
	UploadDay       string `json:"uploadDay"`
	UploadMonth     string `json:"uploadMonth"`
	UploadYear      string `json:"uploadYear"`
	Views           int    `json:"views"`
	Likes           int    `json:"likes"`
	Dislikes        int    `json:"dislikes"`
	Visibility      string `json:"visibility"`
	Viewer          string `json:"viewer"`
	Category        string `json:"category"`
	ChannelName     string `json:"channelName"`
	ChannelPhotoURL string `json:"channelPhotoURL"`
	ChannelEmail    string `json:"channelEmail"`
}

type NewChannel struct {
	Name       string `json:"name"`
	Email      string `json:"email"`
	PhotoURL   string `json:"photoURL"`
	BannerURL  string `json:"bannerURL"`
	Subscriber int    `json:"subscriber"`
	IsPremium  string `json:"isPremium"`
}

type NewVideo struct {
	VideoTitle      string `json:"videoTitle"`
	VideoDesc       string `json:"videoDesc"`
	VideoURL        string `json:"videoURL"`
	VideoThumbnail  string `json:"videoThumbnail"`
	UploadDay       string `json:"uploadDay"`
	UploadMonth     string `json:"uploadMonth"`
	UploadYear      string `json:"uploadYear"`
	Views           int    `json:"views"`
	Likes           int    `json:"likes"`
	Dislikes        int    `json:"dislikes"`
	Visibility      string `json:"visibility"`
	Viewer          string `json:"viewer"`
	Category        string `json:"category"`
	ChannelName     string `json:"channelName"`
	ChannelPhotoURL string `json:"channelPhotoURL"`
	ChannelEmail    string `json:"channelEmail"`
}

type WatchVideo struct {
	Views    int `json:"views"`
	Likes    int `json:"likes"`
	Dislikes int `json:"dislikes"`
}
