// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	PhotoURL   string `json:"photoURL"`
	BannerURL  string `json:"bannerURL"`
	Subscriber int    `json:"subscriber"`
	IsPremium  string `json:"isPremium"`
}

type Comment struct {
	CommentID       string `json:"commentId"`
	VideoID         int    `json:"videoId"`
	ChannelID       int    `json:"channelId"`
	ChannelName     string `json:"channelName"`
	ChannelEmail    string `json:"channelEmail"`
	ChannelPhotoURL string `json:"channelPhotoURL"`
	Content         string `json:"content"`
	ReplyTo         int    `json:"replyTo"`
	Likes           int    `json:"likes"`
	Dislikes        int    `json:"dislikes"`
	Day             int    `json:"day"`
	Month           int    `json:"month"`
	Year            int    `json:"year"`
	Replies         int    `json:"replies"`
}

type CommentDislike struct {
	CommentDislikeID string `json:"commentDislikeId"`
	CommentID        int    `json:"commentId"`
	ChannelID        int    `json:"channelId"`
	ChannelEmail     string `json:"channelEmail"`
}

type CommentLike struct {
	CommentLikeID string `json:"commentLikeId"`
	CommentID     int    `json:"commentId"`
	ChannelID     int    `json:"channelId"`
	ChannelEmail  string `json:"channelEmail"`
}

type Dislike struct {
	DislikeID      string `json:"dislikeId"`
	ChannelID      int    `json:"channelId"`
	ChannelEmail   string `json:"channelEmail"`
	VideoID        int    `json:"videoId"`
	VideoThumbnail string `json:"videoThumbnail"`
	VideoURL       string `json:"videoURL"`
}

type Like struct {
	LikeID         string `json:"likeId"`
	ChannelID      int    `json:"channelId"`
	ChannelEmail   string `json:"channelEmail"`
	VideoID        int    `json:"videoId"`
	VideoThumbnail string `json:"videoThumbnail"`
	VideoURL       string `json:"videoURL"`
}

type Video struct {
	VideoID         string `json:"videoId"`
	VideoTitle      string `json:"videoTitle"`
	VideoDesc       string `json:"videoDesc"`
	VideoURL        string `json:"videoURL"`
	VideoThumbnail  string `json:"videoThumbnail"`
	UploadDay       string `json:"uploadDay"`
	UploadMonth     string `json:"uploadMonth"`
	UploadYear      string `json:"uploadYear"`
	Views           int    `json:"views"`
	Likes           int    `json:"likes"`
	Dislikes        int    `json:"dislikes"`
	Visibility      string `json:"visibility"`
	Viewer          string `json:"viewer"`
	Category        string `json:"category"`
	ChannelName     string `json:"channelName"`
	ChannelPhotoURL string `json:"channelPhotoURL"`
	ChannelEmail    string `json:"channelEmail"`
}

type NewChannel struct {
	Name       string `json:"name"`
	Email      string `json:"email"`
	PhotoURL   string `json:"photoURL"`
	BannerURL  string `json:"bannerURL"`
	Subscriber int    `json:"subscriber"`
	IsPremium  string `json:"isPremium"`
}

type NewComment struct {
	VideoID         int    `json:"videoId"`
	ChannelID       int    `json:"channelId"`
	ChannelName     string `json:"channelName"`
	ChannelEmail    string `json:"channelEmail"`
	ChannelPhotoURL string `json:"channelPhotoURL"`
	Content         string `json:"content"`
	ReplyTo         int    `json:"replyTo"`
	Likes           int    `json:"likes"`
	Dislikes        int    `json:"dislikes"`
	Day             int    `json:"day"`
	Month           int    `json:"month"`
	Year            int    `json:"year"`
	Replies         int    `json:"replies"`
}

type NewCommentDislike struct {
	CommentID    int    `json:"commentId"`
	ChannelID    int    `json:"channelId"`
	ChannelEmail string `json:"channelEmail"`
}

type NewCommentLike struct {
	CommentID    int    `json:"commentId"`
	ChannelID    int    `json:"channelId"`
	ChannelEmail string `json:"channelEmail"`
}

type NewDislike struct {
	ChannelID      int    `json:"channelId"`
	ChannelEmail   string `json:"channelEmail"`
	VideoID        int    `json:"videoId"`
	VideoThumbnail string `json:"videoThumbnail"`
	VideoURL       string `json:"videoURL"`
}

type NewLike struct {
	ChannelID      int    `json:"channelId"`
	ChannelEmail   string `json:"channelEmail"`
	VideoID        int    `json:"videoId"`
	VideoThumbnail string `json:"videoThumbnail"`
	VideoURL       string `json:"videoURL"`
}

type NewVideo struct {
	VideoTitle      string `json:"videoTitle"`
	VideoDesc       string `json:"videoDesc"`
	VideoURL        string `json:"videoURL"`
	VideoThumbnail  string `json:"videoThumbnail"`
	UploadDay       string `json:"uploadDay"`
	UploadMonth     string `json:"uploadMonth"`
	UploadYear      string `json:"uploadYear"`
	Views           int    `json:"views"`
	Likes           int    `json:"likes"`
	Dislikes        int    `json:"dislikes"`
	Visibility      string `json:"visibility"`
	Viewer          string `json:"viewer"`
	Category        string `json:"category"`
	ChannelName     string `json:"channelName"`
	ChannelPhotoURL string `json:"channelPhotoURL"`
	ChannelEmail    string `json:"channelEmail"`
}
